name: Generate & Upload YouTube Short

on:
  workflow_dispatch:  # इससे आप जब चाहें मैन्युअल रूप से भी रन कर सकते हैं
  schedule:
    - cron: '30 0 * * *'   # रोज़ाना सुबह 6:00 बजे (IST)
    - cron: '0 6 * * *'    # रोज़ाना सुबह 11:30 बजे (IST)
    - cron: '30 10 * * *'  # रोज़ाना शाम 4:00 बजे (IST)

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Install Python Dependencies
        run: |
          pip install pytrends edge-tts moviepy==1.0.3 requests Pillow==9.5.0 "imageio[pyav]" imageio-ffmpeg google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run Video Generator & Auto-Upload Script
        # Yahan hum GitHub Secrets ko Python ke Environment Variables me daal rahe hain
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python generate_preview.py

      - name: Clean Up Everything (Repo Stays Clean)
        run: |
          rm -f *.mp4 *.mp3 *.jpg HindiFont.ttf
